export const tasksErrorCodes = {
  TITLE_REQUIRED: "TASKS_TITLE_REQUIRED",
  TITLE_TOO_LONG: "TASKS_TITLE_TOO_LONG",
  NOTES_TOO_LONG: "TASKS_NOTES_TOO_LONG",
  CATEGORY_TOO_LONG: "TASKS_CATEGORY_TOO_LONG",
  SUBCATEGORY_TOO_LONG: "TASKS_SUBCATEGORY_TOO_LONG",
  DUE_DATE_INVALID: "TASKS_DUE_DATE_INVALID",
  ASSIGNEE_NOT_FOUND: "TASKS_ASSIGNEE_NOT_FOUND",
  NOT_FOUND: "TASKS_NOT_FOUND",
  ALREADY_COMPLETED: "TASKS_ALREADY_COMPLETED",
  NOT_AUTHORIZED: "TASKS_NOT_AUTHORIZED",
  COMPLETED_IMMUTABLE: "TASKS_COMPLETED_IMMUTABLE",
  ASSIGNMENT_REQUIRED: "TASKS_ASSIGNMENT_REQUIRED",
  INVALID_STATUS_TRANSITION: "TASKS_INVALID_STATUS_TRANSITION",
  DELETE_IN_PROGRESS: "TASKS_DELETE_IN_PROGRESS",
  ALREADY_ASSIGNED: "TASKS_ALREADY_ASSIGNED",
  RELEASE_TODO_REQUIRED: "TASKS_RELEASE_TODO_REQUIRED",
  NOT_ASSIGNED_TO_USER: "TASKS_NOT_ASSIGNED_TO_USER",
} as const;

export const tasksErrorMessages = {
  TASKS_TITLE_REQUIRED: "Add a title for the task.",
  TASKS_TITLE_TOO_LONG: "That task title is too long.",
  TASKS_NOTES_TOO_LONG: "Those notes are too long.",
  TASKS_CATEGORY_TOO_LONG: "That category is too long.",
  TASKS_SUBCATEGORY_TOO_LONG: "That subcategory is too long.",
  TASKS_DUE_DATE_INVALID: "Pick a valid due date.",
  TASKS_ASSIGNEE_NOT_FOUND: "That person is not part of this wedding.",
  TASKS_NOT_FOUND: "That task could not be found.",
  TASKS_ALREADY_COMPLETED: "That task is already complete.",
  TASKS_NOT_AUTHORIZED: "You do not have permission to change that task.",
  TASKS_COMPLETED_IMMUTABLE: "Completed tasks cannot be edited or deleted.",
  TASKS_ASSIGNMENT_REQUIRED: "Assign this task before moving it forward.",
  TASKS_INVALID_STATUS_TRANSITION: "That task status has changed. Refresh and try again.",
  TASKS_DELETE_IN_PROGRESS: "Move this task back to To do before deleting it.",
  TASKS_ALREADY_ASSIGNED: "That task has already been picked up.",
  TASKS_RELEASE_TODO_REQUIRED: "Move this task back to To do before releasing it.",
  TASKS_NOT_ASSIGNED_TO_USER: "Only the assigned person can release this task.",
} as const;
