/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteRouteImport } from './routes/$slug/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as NewRouteImport } from './routes/new'
import { Route as SlugIndexRouteImport } from './routes/$slug/index'
import { Route as SlugBudgetRouteImport } from './routes/$slug/budget'
import { Route as SlugEventsRouteImport } from './routes/$slug/events'
import { Route as SlugGuestsRouteImport } from './routes/$slug/guests'
import { Route as SlugTasksRouteImport } from './routes/$slug/tasks'
import { Route as SlugVendorsRouteImport } from './routes/$slug/vendors'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthGetStartedRouteImport } from './routes/auth/get-started'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthResendLinkRouteImport } from './routes/auth/resend-link'
import { Route as SlugTasksTaskIdRouteImport } from './routes/$slug/tasks_/$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRouteRoute = SlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugBudgetRoute = SlugBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugEventsRoute = SlugEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugGuestsRoute = SlugGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugTasksRoute = SlugTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugVendorsRoute = SlugVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => SlugRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthGetStartedRoute = AuthGetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResendLinkRoute = AuthResendLinkRouteImport.update({
  id: '/resend-link',
  path: '/resend-link',
  getParentRoute: () => AuthRouteRoute,
} as any)
const SlugTasksTaskIdRoute = SlugTasksTaskIdRouteImport.update({
  id: '/tasks_/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => SlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/new': typeof NewRoute
  '/$slug/budget': typeof SlugBudgetRoute
  '/$slug/events': typeof SlugEventsRoute
  '/$slug/guests': typeof SlugGuestsRoute
  '/$slug/tasks': typeof SlugTasksRoute
  '/$slug/vendors': typeof SlugVendorsRoute
  '/auth/get-started': typeof AuthGetStartedRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/resend-link': typeof AuthResendLinkRoute
  '/$slug/': typeof SlugIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/$slug/tasks/$taskId': typeof SlugTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/$slug/budget': typeof SlugBudgetRoute
  '/$slug/events': typeof SlugEventsRoute
  '/$slug/guests': typeof SlugGuestsRoute
  '/$slug/tasks': typeof SlugTasksRoute
  '/$slug/vendors': typeof SlugVendorsRoute
  '/auth/get-started': typeof AuthGetStartedRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/resend-link': typeof AuthResendLinkRoute
  '/$slug': typeof SlugIndexRoute
  '/auth': typeof AuthIndexRoute
  '/$slug/tasks/$taskId': typeof SlugTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/new': typeof NewRoute
  '/$slug/budget': typeof SlugBudgetRoute
  '/$slug/events': typeof SlugEventsRoute
  '/$slug/guests': typeof SlugGuestsRoute
  '/$slug/tasks': typeof SlugTasksRoute
  '/$slug/vendors': typeof SlugVendorsRoute
  '/auth/get-started': typeof AuthGetStartedRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/resend-link': typeof AuthResendLinkRoute
  '/$slug/': typeof SlugIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/$slug/tasks_/$taskId': typeof SlugTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/auth'
    | '/new'
    | '/$slug/budget'
    | '/$slug/events'
    | '/$slug/guests'
    | '/$slug/tasks'
    | '/$slug/vendors'
    | '/auth/get-started'
    | '/auth/login'
    | '/auth/resend-link'
    | '/$slug/'
    | '/auth/'
    | '/$slug/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/$slug/budget'
    | '/$slug/events'
    | '/$slug/guests'
    | '/$slug/tasks'
    | '/$slug/vendors'
    | '/auth/get-started'
    | '/auth/login'
    | '/auth/resend-link'
    | '/$slug'
    | '/auth'
    | '/$slug/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/auth'
    | '/new'
    | '/$slug/budget'
    | '/$slug/events'
    | '/$slug/guests'
    | '/$slug/tasks'
    | '/$slug/vendors'
    | '/auth/get-started'
    | '/auth/login'
    | '/auth/resend-link'
    | '/$slug/'
    | '/auth/'
    | '/$slug/tasks_/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRouteRoute: typeof SlugRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  NewRoute: typeof NewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/budget': {
      id: '/$slug/budget'
      path: '/budget'
      fullPath: '/$slug/budget'
      preLoaderRoute: typeof SlugBudgetRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/events': {
      id: '/$slug/events'
      path: '/events'
      fullPath: '/$slug/events'
      preLoaderRoute: typeof SlugEventsRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/guests': {
      id: '/$slug/guests'
      path: '/guests'
      fullPath: '/$slug/guests'
      preLoaderRoute: typeof SlugGuestsRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/tasks': {
      id: '/$slug/tasks'
      path: '/tasks'
      fullPath: '/$slug/tasks'
      preLoaderRoute: typeof SlugTasksRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/vendors': {
      id: '/$slug/vendors'
      path: '/vendors'
      fullPath: '/$slug/vendors'
      preLoaderRoute: typeof SlugVendorsRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/get-started': {
      id: '/auth/get-started'
      path: '/get-started'
      fullPath: '/auth/get-started'
      preLoaderRoute: typeof AuthGetStartedRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/resend-link': {
      id: '/auth/resend-link'
      path: '/resend-link'
      fullPath: '/auth/resend-link'
      preLoaderRoute: typeof AuthResendLinkRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/$slug/tasks_/$taskId': {
      id: '/$slug/tasks_/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/$slug/tasks/$taskId'
      preLoaderRoute: typeof SlugTasksTaskIdRouteImport
      parentRoute: typeof SlugRouteRoute
    }
  }
}

interface SlugRouteRouteChildren {
  SlugBudgetRoute: typeof SlugBudgetRoute
  SlugEventsRoute: typeof SlugEventsRoute
  SlugGuestsRoute: typeof SlugGuestsRoute
  SlugTasksRoute: typeof SlugTasksRoute
  SlugVendorsRoute: typeof SlugVendorsRoute
  SlugIndexRoute: typeof SlugIndexRoute
  SlugTasksTaskIdRoute: typeof SlugTasksTaskIdRoute
}

const SlugRouteRouteChildren: SlugRouteRouteChildren = {
  SlugBudgetRoute: SlugBudgetRoute,
  SlugEventsRoute: SlugEventsRoute,
  SlugGuestsRoute: SlugGuestsRoute,
  SlugTasksRoute: SlugTasksRoute,
  SlugVendorsRoute: SlugVendorsRoute,
  SlugIndexRoute: SlugIndexRoute,
  SlugTasksTaskIdRoute: SlugTasksTaskIdRoute,
}

const SlugRouteRouteWithChildren = SlugRouteRoute._addFileChildren(
  SlugRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthGetStartedRoute: typeof AuthGetStartedRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResendLinkRoute: typeof AuthResendLinkRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthGetStartedRoute: AuthGetStartedRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResendLinkRoute: AuthResendLinkRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRouteRoute: SlugRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  NewRoute: NewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
