export const WEDDING_NAME_MAX_LENGTH = 80;
export const COUPLE_NAME_MAX_LENGTH = 80;
export const PLACE_MAX_LENGTH = 80;
export const PLACE_ID_MAX_LENGTH = 256;

export const createWeddingErrorCodes = {
  NAME_REQUIRED: "WEDDINGS_CREATE_WEDDING_NAME_REQUIRED",
  NAME_TOO_LONG: "WEDDINGS_CREATE_WEDDING_NAME_TOO_LONG",
  COUPLE_A_REQUIRED: "WEDDINGS_CREATE_WEDDING_COUPLE_A_REQUIRED",
  COUPLE_B_REQUIRED: "WEDDINGS_CREATE_WEDDING_COUPLE_B_REQUIRED",
  COUPLE_NAME_TOO_LONG: "WEDDINGS_CREATE_WEDDING_COUPLE_NAME_TOO_LONG",
  DATE_INVALID: "WEDDINGS_CREATE_WEDDING_DATE_INVALID",
  DATE_IN_PAST: "WEDDINGS_CREATE_WEDDING_DATE_IN_PAST",
  CITY_TOO_LONG: "WEDDINGS_CREATE_WEDDING_CITY_TOO_LONG",
  COUNTRY_TOO_LONG: "WEDDINGS_CREATE_WEDDING_COUNTRY_TOO_LONG",
  PLACE_REQUIRED: "WEDDINGS_CREATE_WEDDING_PLACE_REQUIRED",
  PLACE_ID_INVALID: "WEDDINGS_CREATE_WEDDING_PLACE_ID_INVALID",
  COORDINATES_INVALID: "WEDDINGS_CREATE_WEDDING_COORDINATES_INVALID",
  INVITE_EMAIL_INVALID: "WEDDINGS_CREATE_WEDDING_INVITE_EMAIL_INVALID",
} as const;

export const createWeddingErrorMessages = {
  WEDDINGS_CREATE_WEDDING_NAME_REQUIRED:
    "Add a name so we can put a label on your wedding.",
  WEDDINGS_CREATE_WEDDING_NAME_TOO_LONG: `That's a bit long, ${WEDDING_NAME_MAX_LENGTH} characters max.`,
  WEDDINGS_CREATE_WEDDING_COUPLE_A_REQUIRED: "Add your name.",
  WEDDINGS_CREATE_WEDDING_COUPLE_B_REQUIRED: "Add your partner's name.",
  WEDDINGS_CREATE_WEDDING_COUPLE_NAME_TOO_LONG: `That's a bit long, ${COUPLE_NAME_MAX_LENGTH} characters max.`,
  WEDDINGS_CREATE_WEDDING_DATE_INVALID: "Pick a real date.",
  WEDDINGS_CREATE_WEDDING_DATE_IN_PAST: "Pick a date from today onward.",
  WEDDINGS_CREATE_WEDDING_CITY_TOO_LONG: `That's a bit long, ${PLACE_MAX_LENGTH} characters max.`,
  WEDDINGS_CREATE_WEDDING_COUNTRY_TOO_LONG: `That's a bit long, ${PLACE_MAX_LENGTH} characters max.`,
  WEDDINGS_CREATE_WEDDING_PLACE_REQUIRED: "Pick a city from the list.",
  WEDDINGS_CREATE_WEDDING_PLACE_ID_INVALID: "Pick a city from the list.",
  WEDDINGS_CREATE_WEDDING_COORDINATES_INVALID:
    "That location doesn't look right.",
  WEDDINGS_CREATE_WEDDING_INVITE_EMAIL_INVALID:
    "That doesn't look like an email.",
} as const;
