export const overviewPosterCards = [
  {
    stableKey: "gazebo-jeremy-wong",
    active: true,
    sortOrder: 5,
    imageKey: "overview/gazebo-jeremy-wong.jpg",
    imageSourceUrl:
      "https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=1800&q=85",
    imageAlt: "A garden gazebo waiting among trees",
    imageCreator: "Jeremy Wong Weddings",
    imageLicense: "Unsplash License",
    caption: "A garden, ready to gather",
    locationCity: "Charleston",
    locationCountry: "United States",
    quote: "You pierce my soul. I am half agony, half hope.",
    author: "Jane Austen",
    sourceTitle: "Persuasion",
    sourceUrl: "https://www.gutenberg.org/files/105/105-h/105-h.htm",
  },
  {
    stableKey: "glasses-photos-by-lanty",
    active: true,
    sortOrder: 6,
    imageKey: "overview/glasses-photos-by-lanty.jpg",
    imageSourceUrl:
      "https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1800&q=85",
    imageAlt: "Rows of wine glasses set for a reception",
    imageCreator: "Photos by Lanty",
    imageLicense: "Unsplash License",
    caption: "The glasses, catching the light",
    locationCity: "Napa",
    locationCountry: "United States",
    quote: "Whatever our souls are made of, his and mine are the same.",
    author: "Emily Bronte",
    sourceTitle: "Wuthering Heights",
    sourceUrl: "https://www.gutenberg.org/files/768/768-h/768-h.htm",
  },
  {
    stableKey: "glasses-evelina-friman",
    active: true,
    sortOrder: 7,
    imageKey: "overview/glasses-evelina-friman.jpg",
    imageSourceUrl:
      "https://images.unsplash.com/photo-1502635385003-ee1e6a1a742d?auto=format&fit=crop&w=1800&q=85",
    imageAlt: "Long-stem glasses on a sunlit table",
    imageCreator: "Evelina Friman",
    imageLicense: "Unsplash License",
    caption: "A table dressed for evening",
    locationCity: "Lisbon",
    locationCountry: "Portugal",
    quote: "I would not wish any companion in the world but you.",
    author: "William Shakespeare",
    sourceTitle: "The Tempest",
    sourceUrl: "https://www.gutenberg.org/files/2235/2235-h/2235-h.htm",
  },
  {
    stableKey: "courtyard-soulseeker",
    active: true,
    sortOrder: 8,
    imageKey: "overview/courtyard-soulseeker.jpg",
    imageSourceUrl:
      "https://images.unsplash.com/photo-1670529776180-60e4132ab90c?auto=format&fit=crop&w=1800&q=85",
    imageAlt: "A courtyard filled with white flowers",
    imageCreator: "Soulseeker - Creative Photography",
    imageLicense: "Unsplash License",
    caption: "A courtyard in bloom",
    locationCity: "Marrakech",
    locationCountry: "Morocco",
    quote: "My bounty is as boundless as the sea, my love as deep.",
    author: "William Shakespeare",
    sourceTitle: "Romeo and Juliet",
    sourceUrl: "https://www.gutenberg.org/files/1513/1513-h/1513-h.htm",
  },
  {
    stableKey: "chairs-water-matthew-essman",
    active: true,
    sortOrder: 9,
    imageKey: "overview/chairs-water-matthew-essman.jpg",
    imageSourceUrl:
      "https://images.unsplash.com/photo-1505944357431-27579db47558?auto=format&fit=crop&w=1800&q=85",
    imageAlt: "White chairs facing a quiet stretch of water",
    imageCreator: "Matthew Essman",
    imageLicense: "Unsplash License",
    caption: "Seats beside the water",
    locationCity: "Cape Town",
    locationCountry: "South Africa",
    quote: "A thing of beauty is a joy for ever.",
    author: "John Keats",
    sourceTitle: "Endymion",
    sourceUrl: "https://www.gutenberg.org/files/24280/24280-h/24280-h.htm",
  },
  {
    stableKey: "night-venue-junior-reis",
    active: true,
    sortOrder: 10,
    imageKey: "overview/night-venue-junior-reis.jpg",
    imageSourceUrl:
      "https://images.unsplash.com/photo-1607861884586-c7cfaed16290?auto=format&fit=crop&w=1800&q=85",
    imageAlt: "A venue glowing after dusk",
    imageCreator: "Junior REIS",
    imageLicense: "Unsplash License",
    caption: "The house, lit for the night",
    locationCity: "Cartagena",
    locationCountry: "Colombia",
    quote: "O my Luve is like a red, red rose.",
    author: "Robert Burns",
    sourceTitle: "A Red, Red Rose",
    sourceUrl: "https://www.gutenberg.org/files/1279/1279-h/1279-h.htm",
  },
  {
    stableKey: "aisle-flowers-shardayyy",
    active: true,
    sortOrder: 11,
    imageKey: "overview/aisle-flowers-shardayyy.jpg",
    imageSourceUrl:
      "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1800&q=85",
    imageAlt: "White and pink flowers lining an aisle",
    imageCreator: "Shardayyy Photography",
    imageLicense: "Unsplash License",
    caption: "Flowers along the aisle",
    locationCity: "Kyoto",
    locationCountry: "Japan",
    quote: "My heart is like a singing bird.",
    author: "Christina Rossetti",
    sourceTitle: "A Birthday",
    sourceUrl: "https://www.gutenberg.org/files/19188/19188-h/19188-h.htm",
  },
  {
    stableKey: "tables-abby-savage",
    active: true,
    sortOrder: 12,
    imageKey: "overview/tables-abby-savage.jpg",
    imageSourceUrl:
      "https://images.unsplash.com/photo-1510076857177-7470076d4098?auto=format&fit=crop&w=1800&q=85",
    imageAlt: "Round tables dressed in white linen",
    imageCreator: "Abby Savage",
    imageLicense: "Unsplash License",
    caption: "Tables waiting for guests",
    locationCity: "Vienna",
    locationCountry: "Austria",
    quote: "If music be the food of love, play on.",
    author: "William Shakespeare",
    sourceTitle: "Twelfth Night",
    sourceUrl: "https://www.gutenberg.org/files/1524/1524-h/1524-h.htm",
  },
  {
    stableKey: "dinnerware-chuttersnap",
    active: true,
    sortOrder: 13,
    imageKey: "overview/dinnerware-chuttersnap.jpg",
    imageSourceUrl:
      "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1800&q=85",
    imageAlt: "White dinnerware set for a meal",
    imageCreator: "CHUTTERSNAP",
    imageLicense: "Unsplash License",
    caption: "Places set with care",
    locationCity: "Amalfi",
    locationCountry: "Italy",
    quote: "No sooner met but they looked, no sooner looked but they loved.",
    author: "William Shakespeare",
    sourceTitle: "As You Like It",
    sourceUrl: "https://www.gutenberg.org/files/1120/1120-h/1120-h.htm",
  },
  {
    stableKey: "window-ben-atkins",
    active: true,
    sortOrder: 14,
    imageKey: "overview/window-ben-atkins.jpg",
    imageSourceUrl:
      "https://images.unsplash.com/photo-1721677337543-37b07e7e28b5?auto=format&fit=crop&w=1800&q=85",
    imageAlt: "An outdoor ceremony seen from a window",
    imageCreator: "Ben Atkins",
    imageLicense: "Unsplash License",
    caption: "The lawn, seen from inside",
    locationCity: "Edinburgh",
    locationCountry: "United Kingdom",
    quote:
      "It is not time or opportunity that is to determine intimacy, it is disposition alone.",
    author: "Jane Austen",
    sourceTitle: "Sense and Sensibility",
    sourceUrl: "https://www.gutenberg.org/files/161/161-h/161-h.htm",
  },
  {
    stableKey: "settings-thomas-william",
    active: true,
    sortOrder: 15,
    imageKey: "overview/settings-thomas-william.jpg",
    imageSourceUrl:
      "https://images.unsplash.com/photo-1524824267900-2fa9cbf7a506?auto=format&fit=crop&w=1800&q=85",
    imageAlt: "Table settings arranged in a quiet room",
    imageCreator: "Thomas William",
    imageLicense: "Unsplash License",
    caption: "A room prepared for supper",
    locationCity: "Oaxaca",
    locationCountry: "Mexico",
    quote:
      "I cannot fix on the hour, or the spot, or the look, or the words, which laid the foundation.",
    author: "Jane Austen",
    sourceTitle: "Pride and Prejudice",
    sourceUrl: "https://www.gutenberg.org/files/1342/1342-h/1342-h.htm",
  },
  {
    stableKey: "house-james-bold",
    active: true,
    sortOrder: 16,
    imageKey: "overview/house-james-bold.jpg",
    imageSourceUrl:
      "https://images.unsplash.com/photo-1521543387600-c745f8e83d77?auto=format&fit=crop&w=1800&q=85",
    imageAlt: "A stone house with closed shutters in daylight",
    imageCreator: "James Bold",
    imageLicense: "Unsplash License",
    caption: "The house that will hold the day",
    locationCity: "Siena",
    locationCountry: "Italy",
    quote: "Tis better to have loved and lost than never to have loved at all.",
    author: "Alfred Tennyson",
    sourceTitle: "In Memoriam A.H.H.",
    sourceUrl: "https://www.gutenberg.org/files/12242/12242-h/12242-h.htm",
  },
  {
    stableKey: "ceremony-jonathan-borba",
    active: true,
    sortOrder: 17,
    imageKey: "overview/ceremony-jonathan-borba.jpg",
    imageSourceUrl:
      "https://images.unsplash.com/photo-1769812344142-00c7f6584885?auto=format&fit=crop&w=1800&q=85",
    imageAlt: "Outdoor chairs and flowers arranged for a ceremony",
    imageCreator: "Jonathan Borba",
    imageLicense: "Unsplash License",
    caption: "An aisle under open sky",
    locationCity: "Salvador",
    locationCountry: "Brazil",
    quote:
      "Love, all love of other sights controls, and makes one little room an everywhere.",
    author: "John Donne",
    sourceTitle: "The Good-Morrow",
    sourceUrl: "https://www.gutenberg.org/files/36522/36522-h/36522-h.htm",
  },
  {
    stableKey: "lake-jose-marroquin",
    active: true,
    sortOrder: 18,
    imageKey: "overview/lake-jose-marroquin.jpg",
    imageSourceUrl:
      "https://images.unsplash.com/photo-1759954644796-0ed43f06715b?auto=format&fit=crop&w=1800&q=85",
    imageAlt: "White chairs and an altar beside trees and water",
    imageCreator: "Jose Marroquin",
    imageLicense: "Unsplash License",
    caption: "A ceremony beside the water",
    locationCity: "Queenstown",
    locationCountry: "New Zealand",
    quote: "We were together. I forget the rest.",
    author: "Walt Whitman",
    sourceTitle: "Leaves of Grass",
    sourceUrl: "https://www.gutenberg.org/files/1322/1322-h/1322-h.htm",
  },
  {
    stableKey: "seating-vidit-goswami",
    active: true,
    sortOrder: 19,
    imageKey: "overview/seating-vidit-goswami.jpg",
    imageSourceUrl:
      "https://images.unsplash.com/photo-1772127822562-a898d9f5733c?auto=format&fit=crop&w=1800&q=85",
    imageAlt: "Elegant outdoor seating arranged for a ceremony",
    imageCreator: "Vidit Goswami",
    imageLicense: "Unsplash License",
    caption: "Seats in the garden shade",
    locationCity: "Jaipur",
    locationCountry: "India",
    quote: "Love one another, but make not a bond of love.",
    author: "Kahlil Gibran",
    sourceTitle: "The Prophet",
    sourceUrl: "https://www.gutenberg.org/files/58585/58585-h/58585-h.htm",
  },
  {
    stableKey: "trees-alexander-mass",
    active: true,
    sortOrder: 20,
    imageKey: "overview/trees-alexander-mass.jpg",
    imageSourceUrl:
      "https://images.unsplash.com/photo-1777312378804-7b31809db220?auto=format&fit=crop&w=1800&q=85",
    imageAlt: "A ceremony taking place under trees",
    imageCreator: "Alexander Mass",
    imageLicense: "Unsplash License",
    caption: "A vow beneath the trees",
    locationCity: "Ubud",
    locationCountry: "Indonesia",
    quote:
      "Nothing in the world is single, all things by a law divine in one spirit meet and mingle.",
    author: "Percy Bysshe Shelley",
    sourceTitle: "Love's Philosophy",
    sourceUrl: "https://www.gutenberg.org/files/4800/4800-h/4800-h.htm",
  },
] as const;
